theme: jekyll-theme-cayman
title: Homework Area
description: Homework will be here.


https://github.com/pjournal/mef04-alialtintas/blob/gh-pages/AliAltintas-HW1.Rmd
https://github.com/pjournal/mef04-alialtintas/blob/gh-pages/HW2-ALIALTINTAS.html





